on: 
  schedule: 
    - cron: '0 6 * * 2'
  workflow_dispatch: 

name: 'acr/jetty/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $ACR ]]; then
          export ACR=acr$RANDOM
          fi
          az acr create \
          --name $ACR \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          
          cd acr/jetty
          
          mvn package
          export ACR_JETTY_IMAGE=jetty:latest
          
          az acr build --registry $ACR --image $ACR_JETTY_IMAGE .
          
          cd ../..
          
          
          export RESULT=$(az acr repository show --name $ACR --image $ACR_JETTY_IMAGE)
          az group delete --name $RESOURCE_GROUP --yes || true
          
          if [[ -z $RESULT ]]; then
          echo "Unable to find $ACR_JETTY_IMAGE image"
          exit 1
          fi