on: 
  schedule: 
    - cron: '0 1 * * 2'
  workflow_dispatch: 

name: 'acr/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $ACR ]]; then
          export ACR=acr$RANDOM
          fi
          az acr create \
          --name $ACR \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          export RESULT=$(az acr show --name $ACR --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Azure Container Registry $ACR was not provisioned properly"
          exit 1
          fi