on: 
  schedule: 
    - cron: '0 3 * * 2'
  workflow_dispatch: 

name: 'acr/create-acrpull-service-principal/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $ACR ]]; then
          export ACR=acr$RANDOM
          fi
          az acr create \
          --name $ACR \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          
          if [[ -z $ACR_PULL_SERVICE_PRINCIPAL_NAME ]]; then
          export ACR_PULL_SERVICE_PRINCIPAL_NAME=acr-pull-$RANDOM
          export ACR_ID=`az acr show --name $ACR --query id --output tsv`
          export ACR_PULL_SERVICE_PRINCIPAL_PASSWORD=`az ad sp create-for-rbac \
          --name http://$ACR_PULL_SERVICE_PRINCIPAL_NAME \
          --scopes $ACR_ID \
          --role acrpull \
          --query password \
          --output tsv`
          export ACR_PULL_SERVICE_PRINCIPAL_ID=`az ad sp show \
          --id http://$ACR_PULL_SERVICE_PRINCIPAL_NAME \
          --query appId \
          --output tsv`
          fi
          
          
          az group delete --name $RESOURCE_GROUP --yes || true
          az ad sp delete --name $ACR_PULL_SERVICE_PRINCIPAL_ID || true
          
          if [[ -z $ACR_PULL_SERVICE_PRINCIPAL_PASSWORD ]]; then
          echo "ACR 'acrpull' service principal password was not found"
          exit 1
          fi
          
          if [[ -z $ACR_PULL_SERVICE_PRINCIPAL_ID ]]; then
          echo "ACR 'acrpull' service principal id was not found"
          exit 1
          fi