on: 
  workflow_dispatch: 

name: 'aks/tomcat/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          sed -i "" "s/ACR/$ACR/g" deployment.yml
          kubectl apply -f deployment.yml