on: 
  schedule: 
    - cron: '0 2 * * 1'
  workflow_dispatch: 

name: 'appservice/delete-plan/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $APPSERVICE_PLAN ]]; then
          export APPSERVICE_PLAN=appservice-plan-$RANDOM
          fi
          az appservice plan create \
          --resource-group $RESOURCE_GROUP \
          --location $REGION \
          --name $APPSERVICE_PLAN \
          --is-linux \
          --sku P1V2
          az appservice plan delete \
          --resource-group $RESOURCE_GROUP \
          --name $APPSERVICE_PLAN \
          --yes
          export RESULT=$(az appservice plan show --resource-group $RESOURCE_GROUP --name $APPSERVICE_PLAN --query provisioningState --output tsv)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" == Succeeded ]]; then
          exit 1
          fi