on: 
  workflow_dispatch: 

name: 'aro/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          export ARO_NAME=aro-$RANDOM
          
          az network vnet create \
          --resource-group $RESOURCE_GROUP \
          --name aro-vnet \
          --address-prefixes 10.0.0.0/22
          
          az network vnet subnet create \
          --resource-group $RESOURCE_GROUP \
          --vnet-name aro-vnet \
          --name aro-master-subnet \
          --address-prefixes 10.0.0.0/23 \
          --service-endpoints Microsoft.ContainerRegistry
          
          az network vnet subnet create \
          --resource-group $RESOURCE_GROUP \
          --vnet-name aro-vnet \
          --name aro-worker-subnet \
          --address-prefixes 10.0.2.0/23 \
          --service-endpoints Microsoft.ContainerRegistry
          
          az network vnet subnet update \
          --name aro-master-subnet \
          --resource-group $RESOURCE_GROUP \
          --vnet-name aro-vnet \
          --disable-private-link-service-network-policies true
          
          az aro create \
          --name $ARO_NAME \
          --resource-group $RESOURCE_GROUP \
          --master-subnet aro-master-subnet \
          --worker-subnet aro-worker-subnet \
          --vnet aro-vnet