on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
name: generate_workflows
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PASSWORD }}
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run GitHub Workflow Generator
      run: |
        rm -rf .github/workflows/*_md.yml
        curl -L https://repo1.maven.org/maven2/com/manorrock/parrot/parrot/21.2.11/parrot-21.2.11.jar -o parrot.jar
        java -jar parrot.jar --baseDirectory . --outputDirectory .github/workflows
        git config --global user.email "noreply@microsoft.com"
        git config --global user.name "Automated workflow"
        git add .
        git commit -a -m "Committing workflows" || true
        git push
