on: 
  workflow_dispatch: 

name: 'storage/enable-static-website/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          az storage blob service-properties update \
          --account-name $STORAGE_ACCOUNT_NAME \
          --static-website \
          --404-document 404.html \
          --index-document index.html
          
          az storage account show \
          --name $STORAGE_ACCOUNT_NAME \
          --query primaryEndpoints.web \
          --output tsv